### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by austinkelleher** [Druotic/dotfiles#1]
I just wanted to say how grateful I am that you open sourced your beautiful dotfiles. I've been waiting for this moment for my entire life. Ever since I was a boy I've asked myself, when will JBeaves open source his dotfiles? Well, today is that day. I couldn't be happier.

/cc @charlieduong94

**Comment by charlieduong94** [comment]
I agree, this is a beautiful repo. Literally crying right now. I can't thank you enough.

/cc @Epitrochoid

**Comment by Epitrochoid** [comment]
I installed these dotfiles and within ten minutes I was able to make 5 contributions to Node core. Truly these are the ambrosia of file based program configuration.

**Comment by Druotic** [comment]
@austinkelleher @charlieduong94 @Epitrochoid I'm glad you all found such incredible value in this project - it was an incredibly large undertaking, but I am truly humbled by your kind words. It's comments like these that keep me motivated to push onward with this project. After I get a v1 release completed, maybe we can entertain the possibility of dotfile swag... t-shirts, perhaps? I hear there are some other projects out there that like to give out free t-shirts, so maybe that'd be a good start toward an eventual IPO.

**Comment by xdumaine** [comment]
This is actually a really good abstraction for mongo when u think about it.

**Comment by charlieduong94** [comment]
I've been using this for about a week now and your `.vimrc` is probably the best I've ever used.

**Comment by austinkelleher** [comment]
I've deleted my dotfiles and started fresh with yours. Thanks again.
