### ISSUE TITLE
Thanks, but no thanks

### ISSUE THREAD

**Issue by wenkesj** [Druotic/dotfiles#2]
I'm having an issue installing this

/cc @charlieduong94 @austinkelleher @xdumaine

Making sure this isn't a duplicate to [#1](https://github.com/Druotic/dotfiles/issues/1)

**Comment by wenkesj** [comment]
Here's what `stdout` says every-time I try to install
```sh
~|⇒ goteem


   _|_|_|     _|_|     _|_|_|_|_|   _|_|_|_|   _|_|_|_|   _|      _|
 _|         _|    _|       _|       _|         _|         _|_|  _|_|
 _|  _|_|   _|    _|       _|       _|_|_|     _|_|_|     _|  _|  _|
 _|    _|   _|    _|       _|       _|         _|         _|      _|
   _|_|_|     _|_|         _|       _|_|_|_|   _|_|_|_|   _|      _|

```

**Comment by Druotic** [comment]
This is probably a duplicate in some way, but who cares. This is an awesome contribution. Shipped.
